#\u6570\u636E\u6E90\u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://106.15.61.38:3306/test01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1765000
      maximum-pool-size: 10
      connection-timeout: 120000
      connection-test-query: SELECT 1
#jpa\u914D\u7F6E
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
#\u65E5\u5FD7\u914D\u7F6E
#logging:
#  level:
#    com.example: debug
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#  pattern:
#    console:  "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

